### ISSUE TITLE
cluster argument in mi.eval throws an error

### ISSUE THREAD

**Issue by Ben4444** [atahk/bucky#2]
Using package version 1.0.5.

When you make a call to mi.eval like: `mi.eval(lm(outcome ~ exposure, data = imputed_data), cluster = cluster_variable)`, an error is returned stating: `Error in enquote(mf$cluster) : object 'mf' not found`.

I believe this is because when defining the mi.eval function in mult-imp.R, the cluster variable is incorporated via: `mthd.plus <- as.character(enquote(mf$cluster)[-1])` on line 27, while the rest of the function references mf.raw. This error should be able to be fixed by changing line 27 to: `mthd.plus <- as.character(enquote(mf.raw$cluster)[-1])`.

As a temporary fix, when I enter: `mf <- match.call()`; `mf$cluster <- "cluster_variable"` before making the call to mi.eval, the function works when the cluster argument is supplied.

**Comment by atahk** [comment]
Thanks for catching this! It should be fixed now.
